### ISSUE TITLE
Framework for trying different color modes

### ISSUE THREAD

**Issue by kornelski** [shssoichiro/oxipng#152]
I'm working on implementing #74 

The problem is that the main loop which tries different compression modes/filters assumes there's a single PNG file, and only IDAT differs.

However, palette sorting makes palette + IDAT dependent, so the compression trials can't just pick a smaller IDAT, they have to also set the right palette to match.

The alpha filtering trials get away with this, because they don't change the image mode, but I'm still not entirely happy with alpha trials running compression trials "internally" as part of reduction, rather than being integrated with the main loop of trials (e.g. the side effect is that verbose mode doesn't show alpha mode compressions tested, and the winning IDAT is recompressed later with the same settings).

So I think some refactoring is needed. That's also related to #145

I could just compress with default settings as part of the palette reduction, same as alpha reductions do it, but that feels like copying&pasting a lot of code, and will perform redundant compressions.

So I'm thinking about introducing an object that will explicitly manage compression trials, which could be given to alpha and palette reductions to add their trials to the queue, so that the progress is properly displayed and the best IDAT is saved.

WDYT?

**Comment by shssoichiro** [comment]
On one hand, this makes sense. My concern, however, and the reason I implemented alpha reductions as separate compression tries, is to avoid an exponential increase in number of trials. For example, a full alpha optimization will currently run 6 trials, one for each alpha setting, and after choosing the best, then runs through the normal number of trials (e.g. 48), for a total of 48 + 6 trials. If we aren't careful, we could end up running 48 * 6 trials, and explode the time oxipng takes. If we can avoid that problem, I'm onboard with this refactor.

**Comment by kornelski** [comment]
I've also found a case where reducing an image to 4 bits compresses better than 2-bit image. That would need compression-based check, too.

So my current thinking is:

1. Pick one fast and reasonably representative compression setting, e.g. f=0 zs=0 zx=6 (perhaps level depending on `-o` setting)
2. Immediately recompress IDAT with that setting, and keep it (or at least make note of the size)
3. After each reduction, compress with that setting and keep the reduction only if it compresses same or better.

Unfortunately, this means order of reductions matters, but checking of multiple permutations of reductions would be too expensive.

The step 2 has to exist, since comparing against compressed IDAT already in the file will give false negatives, e.g. zopfli-compressed bad color mode may seem better than good color mode that hasn't been compressed hard enough yet.

**Comment by andrews05** [comment]
@kornelski Don't suppose you still have that image that was better at 4-bit than 2-bit? Would be helpful to add such an image to the tests.

**Comment by kornelski** [comment]
No, I don't remember which exact image I was talking about. Try something with monochrome dithering.

**Comment by andrews05** [comment]
@kornelski Was there anything further to be done here? The framework you implemented appears to work very well 🙂
